export const RELAY_PROTOCOL_VERSION = 1;

export const ROUTE_BYTES = 32;
export const ROUTE_LENGTH = 43;
export const ROUTE_PATTERN = /^[A-Za-z0-9_-]{43}$/;

export const SYSTEM_CONNECTION_ID = 0;
export const MIN_CONNECTION_ID = 1;
export const MAX_CONNECTION_ID = 0xffff_ffff;

export const TARGET_ENVELOPE_HEADER_BYTES = 10;
export const MAX_PAYLOAD_BYTES = 1024 * 1024;
export const MAX_TARGET_FRAME_BYTES =
  TARGET_ENVELOPE_HEADER_BYTES + MAX_PAYLOAD_BYTES;
export const MAX_CONTROL_PAYLOAD_BYTES = 512;

export const MAX_CONTROLLERS = 16;
export const MAX_CONNECTION_ATTEMPTS_PER_MINUTE = 16;
export const MAX_TARGET_CONNECTION_ATTEMPTS_PER_MINUTE = 32;

export const CLOSE_CODE_PROTOCOL_ERROR = 4400;
export const CLOSE_CODE_TARGET_UNAVAILABLE = 4404;
export const CLOSE_CODE_DELIVERY_FAILED = 4408;
export const CLOSE_CODE_INTERNAL_ERROR = 4411;
